---
title: "Canary in the Coal Mine: Anti-NGO Legislation as a Predictor of Civil Society Repression"
short-title: "Canary in the Coal Mine"
author:
- name: Suparna Chaudhry
  affiliation: Lewis & Clark College
  email: schaudhry@lclark.edu
  url: http://www.suparnachaudhry.com/
- name: Andrew Heiss
  affiliation: Georgia State University
  email: aheiss@gsu.edu
  url: https://www.andrewheiss.com/
date: "March 23, 2021"
published: This is an early draft of a working paper.
git-repo: https://github.com/andrewheiss/canary-ngos
abstract: >-
  Many countries across the globe are increasingly cracking down on civil society groups through legal restrictions. While research on democratic backsliding has tended to focus on rights and institutions in the electoral arena, this new wave of attempts to repress civil society organization-many of which are sanctioned by law—represent a bureaucratic form of repression that could be indicative of more severe human rights abuses and backsliding. This is especially the case for electoral democracies, which unlike autocracies do not aggressively and openly attack civic space. In this paper, we ask: do crackdowns on NGOs predict broader civil society repression? We argue that this is the case because anti-NGO laws are among the most subtle means of repression and attract the least least domestic and international condemnation, as many audiences mistake this repression as regulation and are not personally affected by it. These laws also make it easier for states to prevent and deter future large-scale popular mobilization. Using original data on civil society restrictions over the last three decades, we test whether NGO crackdown is a predictor of attacks on journalists, independent media, academic freedom, and freedoms of expression and association. This project has important implications: if crackdown on NGOs is indeed an early warning, it can potentially prevent further deteriorations in space for civil society. 
keywords: "civil society restrictions, human rights, journalists"
reference-section-title: References
bibliography: bibliography.bib
csl: pandoc/csl/chicago-author-date.csl
title-page: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Figure out output format
is_docx <- knitr::pandoc_to("docx") | knitr::pandoc_to("odt")
is_latex <- knitr::pandoc_to("latex")
is_html <- knitr::pandoc_to("html")

# Word-specific things
table_format <- ifelse(is_docx, "huxtable", "kableExtra")  # Huxtable tables
conditional_dpi <- ifelse(is_docx, 300, 300)  # Higher DPI
conditional_align <- ifelse(is_docx, "default", "center")  # Word doesn't support align

# Knitr options
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE,
  tidy.opts = list(width.cutoff = 120),  # Code width
  fig.retina = 3, dpi = conditional_dpi,
  fig.width = 7, fig.asp = 0.618,
  fig.align = conditional_align, out.width = "85%",
  fig.path = "output/figures/",
  cache.path = "output/_cache/",
  fig.process = function(x) {  # Remove "-1" from figure names
    x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
    if (file.rename(x, x2)) x2 else x
  }
)

# R options
options(
  width = 90,  # Output width
  dplyr.summarise.inform = FALSE,  # Turn off dplyr's summarize() auto messages
  knitr.kable.NA = "",  # Make NAs blank in kables
  kableExtra.latex.load_packages = FALSE,  # Don't add LaTeX preamble stuff
  modelsummary_default = table_format  # Set modelsummary backend
)

library(tidyverse)
library(here)

source(here("lib", "graphics.R"))
```

Governments across the globe have been cracking down on civil society organizations (CSOs) -- a phenomenon referred to as closing civic space or shrinking civic space (Carothers & Brechenmacher, 2014; Dupuy, Ron, & Prakash, 2016; Chaudhry, 2016; Dupuy & Prakash, 2018). The non-violent nature of this repression is particularly notable. The last two decades have seen a proliferation of steps designed to limit the influence of civil society organizations, with more than 100 countries obstructing, repressing, or foricbly shutting down non-governmental organizations (NGOs). Since 2013, 91 countries had proposed or enacted 244 measures restricting civil society [@icnl:2021]. In Human Rights Watch's 2016 World Report, Executive Director Kenneth Roth argued that civil society was under more aggressive attack than at any time in recent memory, and over the past decade, the majority of the world has seen a substantial narrowing of allowable civic space. As seen in Figure \@ref(fig:civicus-map), by the end of 2020, only `r civicus$Open$prop_nice` of countries had open and unrestricted civil societies [@civicusmonitor; @ChaudhryHeiss:2021].

Such hostility is not unique to autocratic governments or even “illiberal democracies” – as ViktorOrban referred to in his vision for Hungary [https://www.foreignaffairs.com/articles/central-europe/2018-04-06/how-illiberal-leaders-attack-civil-society]. It is increasingly pervasive, including amongdemocracies. Over the past decade, India has canceled the licenses of tens of thousands of NGOs. It also targeted major groups such as Greenpeace International and Ford Foundation (Press Trust of India. (2019, December 4). 14,5000 NGOs banned by government from receiving foreign funds. LiveMint. Retrieved from: https://www.livemint.com/news/india/14-500-ngos-banned-by-govt-from-receiving-foreign-funds-11575456836000.html). In Canada, several prominentenvironmental NGOs were targeted for opposing the Northern Gateway pipeline and Canadian mining companies’ initiatives abroad [Achtenberg. 1992. \Environmental Advocacy: Challenges to Environmental Groups Rightsto Assemble, Associate and Express their Opinions." Global Trends in NGO Law 7(1)].

There is no doubt that violent attacks on these groups are often an effective means of curbing dissent. But states have also started implementing ‘administrative crackdown,’ or the passage of laws to create barriers to entry, funding, and advocacy by NGOs (Chaudhry, 2016). The use of legal tools instead of violent repression means that NGOs have to adapt their practices to stay within the bounds of permitted activities and operations. While in some cases this has led to the depoliticization of NGOs and avoidance of direct political activism by CSOs, states cannot soften or neutralize all forms of political activities in subtle, legal ways that they have with NGOs. Sooner or later, states need to deal with threats in a more violent, confrontational manner. Studying these NGO laws can thus be the canary in the coal mine which signals the states which intend to continue down this repressive path. What does state targeting of NGOs tell us about a state's broader respect for civil society and the overall level of human rights repression? Can the crackdown on NGOs act as an indicator for subsequent increasing repression?

ARGUMENT, METHODS, AND FINDINGS. 
In this paper, we argue that information about NGO crackdown can be a valuable indicator of human rights trajectories. Such crackdown can act as an early warning signal for worsening repression, suggesting which countries are testing the waters with comparatively 'milder' forms of repression before enacting more violent forms of crackdown. To assess if attacks on NGOs and activists can provide us useful information about future repression, we use an original dataset on state crackdown on NGOs using legal repression across all countries from 1990-2013. WHAT ELSE DO WE USE. Our analysis shows FILL
MAKE DIFFERENCE BETWEEN DE JURE AND DE FACTO CLEAR


Our paper makes an important contribution in predicting (IS THIS THE RIGHT WORD) the onset of repressive state policies. While structural factors such as levels of democracy, economic development, electoral competitiveness can identify countries that are likely to have more or less respect for civic freedoms, these factors are also slow to change over time. As such, they may not be particularly suitable for forecasting short-term trajectories, especially for moderatively repressive countries. On the other hand, state repression of NGOs is more dynamic and provides information about changing levels of human rights standards and repression in subsequent years. 

Below, we first look at existing literature on repression and political violence, outlining state motivations to repress NGOs. We then elaborate on why attacking NGOs may be an important predictor of subsequent repression. Using both original data as well as data from the V-DEM dataset, we show that ...

# Assessing Changes in Government Repression

Repression is the use of coercive action against an individual or organization, within the territorial jurisdiction of the state, for the purpose of imposing a cost on the target as well as deterring specific activities and/or beliefs perceived to be challenging to government personnel, practices, or institutions (Goldstein 1978, xxvii; Poe and Tate 1994; Davenport 2007b; and Ritter and Conrad 2016).

One part of the existing literature focuses on the role of structural factors such as levels of democracy, economic development, electoral competitiveness in predisposing a state to increased use of repression. Most notably, both democracies and democratization is found to have a pacifying effect on state repression (Davenport and Armstrong 2004, Krain 1997, Richards 1999). Democracies are found to have a negative effect on repression largely because of the increased probability of sanctions against authorities for undesirable behavior (Davenport 2007, 41).

Another strand of research focuses on how the behavior of various actors shapes government response. One of the most consistent findings in the political violence literature is that authorities repress to counter ongoing challenges to the status quo. In other words, dissent increases repressive behavior (Davenport 2007).  However, dissent and repression have an endogenous relationship - state authorities also frequently engage in preventive repression to undermine or restrict groups’ abilities to dissent (Ritter and Conrad 2016; and Conrad and Ritter 2019.) In addition to attacking groups’ willingness to organize against states, such
preventive repression also damages their capacity to impose costs (Davenport 2007a, 47.) 

NGOs are one actor that can pose challenges to political authorities, and state repression of these actors, especially through legal restrictions or administrative crackdown can also be considered a form of preventive repression. Below, we explore why government repress NGOs, especially through subtle, legal means. 


## State repression of NGOs and effects on subsequent repression

A robust, strong civil society is widely considered as an important component on democratic transition and consolidation (Putnam). Politically, as important civil society actors, NGOs enable citizens to voice their grievances, seek redress, and carry out lobbying and advocacy activities to further their interests. They help keep government accountable, monitor human rights violations and corruption. From an economic perspective, NGOs provide services when the state falls short. 

As a result of these roles, NGOs can wield real influence, which can be threatening to states. State crackdown on NGOs has become pervasive as these organizations have the ability to influence electoral politics (Dupuy, Ron, and Prakash 2016, Weiss 2009), aid mobilization (Murdie and Bhasin 2011; Bell et al. 2013; and Boulding 2014), and threaten a state’s economic interests (Dietrich and Murdie 2017; Lebovic and Voeten 2009; and Nielsen 2013.). 

There is no doubt that violence is often effective at curbing dissent. But it can also backfire,leading to widespread protests, decreasing leaders’ legitimacy, while increasing their criminalliability (Kim and Sikkink 2010, Sikkink 2011). In contrast to violence, administrative crackdown has fewer adverse consequences – citizens may see it as regulation rather than repression, resulting in little to no counter-mobilization. It may also circumvent concerns among state security or bureaucratic agents about illegitimate orders based on violent repression (Stephan and Chenoweth, 2008). The international consequences are also fewer, since laws, unlike violence, rarely invite condemnation or threats of aid withdrawal (Carothers and Brechenmacher 2014).

We argue that this crackdown on NGOs foreshadows future government transgressions. Leaders want to avoid accountability. Civil society organizations, including NGOs, can help shape the narrative of leaders' performance both domestically and internationally. Monitoring by NGOs and subsequent shaming caninclude significant external revenue loss to states in the form of loss of aid, trade, andforeign direct investments (Keck and Sikkink 1998; and Barry, Chad Clay, and Flynn 2013)

Government attempts to repress NGOs for the above can be the beginning of a deteriorating human rights situation. Such repression reflects the government's willingness and capability to use measures that can make it avoid accountability. Once a state targets NGOs, over time it may grow less hesitant to apply repression more widely. 

In exploring the impact of state crackdown on NGOs on subsequent human rights conditions, we look at both de jure steps-formal legislation that seeks to repress NGOs, as well as the de facto implementation of these steps. This is because while states may pass anti-NGO laws, these laws can also lie dormant. For instance, Russia passed its 2015 Undesirable Organizations Law with the purpose of targeting and eliminating specific foreign-connected NGOs it deemed dangerous. One of the law's sponsors, Aleksandr Tarnavsky, described the law as a preventative measure that would not affect the majority of NGOs working in Russia. Rather, the law would be a "weapon hanging on the wall that never fires" and stand as a warning to potentially uncooperative NGOs [@Kozenko:2015].

Simply noting the passage of (or counting) these laws may therefore miss the effect of their de facto implementation. Moreover, the implementation of these laws may not be limited to its legal character. The govenment may also engage in harassment of NGOs and activists to dissuage NGOs from operation or expressing themselves. This may include measures such as detentions, short-term incarceration, as well as beatings, threats to families and destruction of valuable property.

As prior research in Egypt, Ethiopia and Russia points out, "rather than systematically enforcing all repressive legal measures-often impossible owing to capacity constraints," governments may choose to use extra-legal means to intimidate, harass or prosecute a few NGOs or activists. These cases, especially during moments or crises or contention, "highlight to the wider NGO community-and citizenry-that the government is willing and capable of using the law to repress dissent." [https://carnegieendowment.org/2017/05/18/repression-and-responses-cross-cutting-themes-pub-69961]


- Expectation 1a [de jure]: If a country imposes an anti-NGO law, then it is likely to signal subsequent deteriorating human rights conditions
- 
- Expectation 1b [de facto]: If a country represses CSOs, then it is likely to see subsequent deteriorating human rights conditions




# Methods


I WANTED TO KEEP THE HYPOTHESES SIMPLE, YOU CAN TALK ABOUT THE DIFFERENT MEASURES HERE
- Expectation 1a: Imposing an anti-NGO law (Chaudhry; total, advocacy, entry, funding) is likely to signal deteriorating human rights conditions: political terror (`PTS`)
- E1b: Imposing an anti-NGO law (Chaudhry; total, advocacy, entry, funding) is likely to signal deteriorating human rights conditions: physical violence (`v2x_clphy`)
- E1c: Imposing an anti-NGO law (Chaudhry; total, advocacy, entry, funding) is likely to signal deteriorating human rights conditions: private civil liberties (`v2x_clpriv`)

- E2a: The reduction of civic space (`v2csreprss`) is likely to signal deteriorating human rights conditions: political terror (`PTS`)
- E2b: The reduction of civic space (`v2csreprss`) is likely to signal deteriorating human rights conditions: physical violence (`v2x_clphy`)
- E2c: The reduction of civic space (`v2csreprss`) is likely to signal deteriorating human rights conditions: private civil liberties (`v2x_clpriv`)

# Results and Analysis

# Conclusion and Implications
Strengthening civil society is an important precondition for democratic transition andconsolidation. It keeps governments accountable and protects civilians from the worst excessesof an abusive government
