---
title: "E~2~: Civil society environment predicts deteriorating human rights"
author: "Suparna Chaudhry and Andrew Heiss"
date: "Last run: `r format(Sys.time(), '%F')`"
output: 
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
knit_print.data.frame <- function(x, ...) {
  res <- paste(c('', '', kable_styling(kable(x, booktabs = TRUE))), collapse = '\n')
  asis_output(res)
}

registerS3method("knit_print", "data.frame", knit_print.data.frame)
registerS3method("knit_print", "grouped_df", knit_print.data.frame)

knitr::opts_chunk$set(fig.retina = 3,
                      tidy.opts = list(width.cutoff = 120),  # For code
                      options(width = 90),  # For output
                      fig.asp = 0.618, fig.width = 7, 
                      fig.align = "center", out.width = "85%")

options(dplyr.summarise.inform = FALSE,
        knitr.kable.NA = "")
```

```{r load-libraries-data, message=FALSE, warning=FALSE}
library(tidyverse)
library(targets)
library(broom)
library(broom.mixed)
library(tidybayes)
library(glue)
library(brms)
library(scales)
library(kableExtra)
library(modelsummary)
library(here)

# Generated via random.org
set.seed(9936)

# Load data and models
withr::with_dir(here::here(), {
  source(tar_read(plot_funs))
  
  # Load big list of models
  model_df <- tar_read(model_df) %>% 
    filter(str_detect(model, "baseline") | str_detect(model, "v2csreprss"))
  
  # Load actual model objects
  tar_load(c(m_pts_baseline, m_pts_v2csreprss, 
             m_pts_baseline_rewb, m_pts_v2csreprss_rewb, 
             m_clphy_baseline, m_clphy_v2csreprss, 
             m_clphy_baseline_rewb, m_clphy_v2csreprss_rewb, 
             m_clpriv_baseline, m_clpriv_v2csreprss, 
             m_clpriv_baseline_rewb, m_clpriv_v2csreprss_rewb))
  
  # Load regression tables
  tar_load(c(models_tbl_e2a, models_tbl_e2b, models_tbl_e2c))
  
  # Load lookup list for coefficients in regression tables
  tar_load(coef_list)
})
```

```{r clean-data, message=FALSE, warning=FALSE}
models <- model_df %>% 
  mutate(actual_model = model %>% map(~eval(rlang::sym(.)))) %>% 
  mutate(across(c(outcome_var, explan_var, re, family), ~fct_inorder(., ordered = TRUE)))

coefs_clean <- tribble(
  ~coef, ~coef_clean,
  "b_v2csreprss", "Civil society repression",
  "b_v2csreprss_lag1", "Civil society repression (t - 1)",
  "b_v2csreprss_within", "Civil society repression (within)",
  "b_v2csreprss_lag1_within", "Civil society repression (within; t - 1)"
) %>% 
  mutate(across(everything(), ~fct_inorder(., ordered = TRUE))) %>% 
  mutate(lagging = str_detect(coef, "lag1"))
```


# E~2a~: Civil society environment and political terror

## Results table

```{r tbl-e2a}
# Build nicer column names
models_for_table_e2a <- models %>% 
  filter(outcome_var == "Political terror") %>% 
  mutate(outcome_var = recode(outcome_var, "Political terror" = "PTS"),
         explan_var = recode(explan_var, "Civil society repression" = "CS repression")) %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

# Make a named vector of original model names and nice names
model_names_tbl_e2a <- models_for_table_e2a %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e2a$model)

# Rename the columns
names(models_tbl_e2a) <- recode(names(models_tbl_e2a), !!!model_names_tbl_e2a)

modelsummary(models_tbl_e2a,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

## Coefficients

```{r plot-coefs-e2a}
coef_plots <- models %>% 
  filter(str_detect(model, "m_pts_v2csreprss")) %>% 
  mutate(re_fancy = case_when(
    re == "RE" ~ "Random effects models",
    re == "REWB" ~ "Random effects—within/between models"
  )) %>% 
  mutate(coef_draws = map(
    actual_model, 
    ~gather_draws(model = ., `b_v2csreprss.*`, regex = TRUE))) %>% 
  select(-actual_model) %>% 
  unnest(coef_draws) %>% 
  filter(!str_detect(.variable, "between")) %>% 
  left_join(coefs_clean, by = c(".variable" = "coef"))

coef_plots %>% 
  ggplot(aes(y = fct_rev(coef_clean), x = .value, fill = re_fancy)) +
  stat_halfeye(aes(alpha = lagging), .width = c(0.8, 0.95)) +
  geom_vline(xintercept = 0) +
  guides(fill = FALSE, alpha = FALSE) +
  scale_alpha_manual(values = c(1, 0.4)) +
  labs(x = "Coefficient", y = NULL) +
  facet_wrap(vars(re_fancy), ncol = 1, scales = "free_y") +
  theme_ngo()
```


## Marginal effects

```{r plot-mfx-e2a}
mfx <- models %>% 
  filter(str_detect(model, "m_pts_v2csreprss")) %>% 
  mutate(plot_vars = case_when(
    re == "RE" ~ "v2csreprss",
    re == "REWB" ~ "v2csreprss_within"
  )) %>% 
  mutate(fx = map2(actual_model, plot_vars, 
                   ~conditional_effects(.x, effects = .y,
                                        categorical = TRUE)[[1]])) %>% 
  select(-actual_model) %>% 
  unnest(fx)

mfx %>% 
  filter(model == "m_pts_v2csreprss") %>% 
  ggplot(aes(x = effect1__, y = estimate__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.4, color = NA) +
  geom_line(size = 1) +
  labs(x = "Civil society repression\n(higher values = less repression)",
       y = "Predicted probability of category",
       color = "Political terror scale", fill = "Political terror scale") +
  theme_ngo()

mfx %>% 
  filter(model == "m_pts_v2csreprss_rewb") %>% 
  ggplot(aes(x = effect1__, y = estimate__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.4, color = NA) +
  geom_line(size = 1) +
  labs(x = "Difference from average level of civil society repression\n(higher values = less repression)",
       y = "Predicted probability of category",
       color = "Political terror scale", fill = "Political terror scale") +
  theme_ngo()
```

\ 

# E~2b~: Civil society environment and physical violence

## Results table

```{r tbl-e2b}
# Build nicer column names
models_for_table_e2b <- models %>% 
  filter(outcome_var == "Physical violence") %>% 
  mutate(explan_var = recode(explan_var, "Civil society repression" = "CS repression")) %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

# Make a named vector of original model names and nice names
model_names_tbl_e2b <- models_for_table_e2b %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e2b$model)

# Rename the columns
names(models_tbl_e2b) <- recode(names(models_tbl_e2b), !!!model_names_tbl_e2b)

modelsummary(models_tbl_e2b,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

## Coefficients

```{r plot-coefs-e2b}
coef_plots <- models %>% 
  filter(str_detect(model, "m_clphy_v2csreprss")) %>% 
  mutate(re_fancy = case_when(
    re == "RE" ~ "Random effects models",
    re == "REWB" ~ "Random effects—within/between models"
  )) %>% 
  mutate(coef_draws = map(
    actual_model, 
    ~gather_draws(model = ., `b_v2csreprss.*`, regex = TRUE))) %>% 
  select(-actual_model) %>% 
  unnest(coef_draws) %>% 
  filter(!str_detect(.variable, "between")) %>% 
  left_join(coefs_clean, by = c(".variable" = "coef"))

coef_plots %>% 
  ggplot(aes(y = fct_rev(coef_clean), x = .value, fill = re_fancy)) +
  stat_halfeye(aes(alpha = lagging), .width = c(0.8, 0.95)) +
  geom_vline(xintercept = 0) +
  guides(fill = FALSE, alpha = FALSE) +
  scale_alpha_manual(values = c(1, 0.4)) +
  labs(x = "Coefficient", y = NULL) +
  facet_wrap(vars(re_fancy), ncol = 1, scales = "free_y") +
  theme_ngo()
```

## Marginal effects

```{r plot-mfx-e2b}
mfx <- models %>% 
  filter(str_detect(model, "m_clphy_v2csreprss")) %>% 
  mutate(plot_vars = case_when(
    re == "RE" ~ "v2csreprss",
    re == "REWB" ~ "v2csreprss_within"
  )) %>% 
  mutate(fx = map2(actual_model, plot_vars, 
                   ~conditional_effects(.x, effects = .y)[[1]])) %>% 
  select(-actual_model) %>% 
  unnest(fx)

mfx %>% 
  filter(model == "m_clphy_v2csreprss") %>% 
  ggplot(aes(x = effect1__, y = estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.4, 
              fill = "#FF4136", color = NA) +
  geom_line(size = 1, color = "#FF4136") +
  labs(x = "Civil society repression\n(higher values = less repression)",
       y = "Predicted physical violence index\n(higher values = less violence)") +
  theme_ngo()

mfx %>% 
  filter(model == "m_clphy_v2csreprss_rewb") %>% 
  ggplot(aes(x = effect1__, y = estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.4, 
              fill = "#FF4136", color = NA) +
  geom_line(size = 1, color = "#FF4136") +
  labs(x = "Difference from average level of civil society repression\n(higher values = less repression)",
       y = "Predicted physical violence index\n(higher values = less violence)") +
  theme_ngo()
```

\ 

# E~2c~: Civil society environment and civil liberties

```{r tbl-e2c}
# Build nicer column names
models_for_table_e2c <- models %>% 
  filter(outcome_var == "Private civil liberties") %>% 
  mutate(explan_var = recode(explan_var, "Civil society repression" = "CS repression")) %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

# Make a named vector of original model names and nice names
model_names_tbl_e2c <- models_for_table_e2c %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e2c$model)

# Rename the columns
names(models_tbl_e2c) <- recode(names(models_tbl_e2c), !!!model_names_tbl_e2c)

modelsummary(models_tbl_e2c,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

## Coefficients

```{r plot-coefs-e2c}
coef_plots <- models %>% 
  filter(str_detect(model, "m_clpriv_v2csreprss")) %>% 
  mutate(re_fancy = case_when(
    re == "RE" ~ "Random effects models",
    re == "REWB" ~ "Random effects—within/between models"
  )) %>% 
  mutate(coef_draws = map(
    actual_model, 
    ~gather_draws(model = ., `b_v2csreprss.*`, regex = TRUE))) %>% 
  select(-actual_model) %>% 
  unnest(coef_draws) %>% 
  filter(!str_detect(.variable, "between")) %>% 
  left_join(coefs_clean, by = c(".variable" = "coef"))

coef_plots %>% 
  ggplot(aes(y = fct_rev(coef_clean), x = .value, fill = re_fancy)) +
  stat_halfeye(aes(alpha = lagging), .width = c(0.8, 0.95)) +
  geom_vline(xintercept = 0) +
  guides(fill = FALSE, alpha = FALSE) +
  scale_alpha_manual(values = c(1, 0.4)) +
  labs(x = "Coefficient", y = NULL) +
  facet_wrap(vars(re_fancy), ncol = 1, scales = "free_y") +
  theme_ngo()
```

## Marginal effects

```{r plot-mfx-e2c}
mfx <- models %>% 
  filter(str_detect(model, "m_clpriv_v2csreprss")) %>% 
  mutate(plot_vars = case_when(
    re == "RE" ~ "v2csreprss",
    re == "REWB" ~ "v2csreprss_within"
  )) %>% 
  mutate(fx = map2(actual_model, plot_vars, 
                   ~conditional_effects(.x, effects = .y)[[1]])) %>% 
  select(-actual_model) %>% 
  unnest(fx)

mfx %>% 
  filter(model == "m_clpriv_v2csreprss") %>% 
  ggplot(aes(x = effect1__, y = estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.4, 
              fill = "#FF4136", color = NA) +
  geom_line(size = 1, color = "#FF4136") +
  labs(x = "Civil society repression\n(higher values = less repression)",
       y = "Predicted civil liberties index\n(higher values = less violence)") +
  theme_ngo()

mfx %>% 
  filter(model == "m_clpriv_v2csreprss_rewb") %>% 
  ggplot(aes(x = effect1__, y = estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.4, 
              fill = "#FF4136", color = NA) +
  geom_line(size = 1, color = "#FF4136") +
  labs(x = "Difference from average level of civil society repression\n(higher values = less repression)",
       y = "Predicted civil liberties index\n(higher values = less violence)") +
  theme_ngo()
```
