---
title: "E~1~: Laws predict deteriorating human rights"
author: "Suparna Chaudhry and Andrew Heiss"
date: "Last run: `r format(Sys.time(), '%F')`"
output: 
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
knit_print.data.frame <- function(x, ...) {
  res <- paste(c('', '', kable_styling(kable(x, booktabs = TRUE))), collapse = '\n')
  asis_output(res)
}

registerS3method("knit_print", "data.frame", knit_print.data.frame)
registerS3method("knit_print", "grouped_df", knit_print.data.frame)

knitr::opts_chunk$set(fig.retina = 3,
                      tidy.opts = list(width.cutoff = 120),  # For code
                      options(width = 90),  # For output
                      fig.asp = 0.618, fig.width = 7, 
                      fig.align = "center", out.width = "85%")

options(dplyr.summarise.inform = FALSE,
        knitr.kable.NA = "")
```

```{r load-libraries-data, message=FALSE, warning=FALSE}
library(tidyverse)
library(targets)
library(broom)
library(broom.mixed)
library(tidybayes)
library(glue)
library(brms)
library(scales)
library(kableExtra)
library(modelsummary)
library(lubridate)
library(here)

# Generated via random.org
set.seed(9936)

# Load data and models
withr::with_dir(here::here(), {
  source(tar_read(plot_funs))
  
  # Load big list of models
  model_df <- tar_read(model_df) %>% 
    filter(!str_detect(model, "v2csreprss"))
  
  # Load actual model objects
  tar_load(c(m_pts_baseline, m_pts_total, m_pts_advocacy, m_pts_entry, m_pts_funding, 
             m_pts_baseline_rewb, m_pts_total_rewb, m_pts_advocacy_rewb, m_pts_entry_rewb, m_pts_funding_rewb, 
             m_clphy_baseline, m_clphy_total, m_clphy_advocacy, m_clphy_entry, m_clphy_funding, 
             m_clphy_baseline_rewb, m_clphy_total_rewb, m_clphy_advocacy_rewb, m_clphy_entry_rewb, m_clphy_funding_rewb, 
             m_clpriv_baseline, m_clpriv_total, m_clpriv_advocacy, m_clpriv_entry, m_clpriv_funding, 
             m_clpriv_baseline_rewb, m_clpriv_total_rewb, m_clpriv_advocacy_rewb, m_clpriv_entry_rewb, m_clpriv_funding_rewb))
  
  # Load regression tables
  tar_load(c(models_tbl_e1a_re, models_tbl_e1a_rewb, 
             models_tbl_e1b_re, models_tbl_e1c_re))
  
  # Load lookup list for coefficients in regression tables
  tar_load(coef_list)
})
```

```{r clean-data}
models <- model_df %>% 
  mutate(actual_model = model %>% map(~eval(rlang::sym(.)))) %>% 
  mutate(across(c(outcome_var, explan_var, re, family), ~fct_inorder(., ordered = TRUE)))

coefs_clean <- tribble(
  ~coef, ~coef_clean,
  "b_barriers_total", "Total legal barriers",
  "b_barriers_total_lag1", "Total legal barriers (t - 1)",
  "b_advocacy", "Barriers to advocacy",
  "b_advocacy_lag1", "Barriers to advocacy (t - 1)",
  "b_entry", "Barriers to entry",
  "b_entry_lag1", "Barriers to entry (t - 1)",
  "b_funding", "Barriers to funding",
  "b_funding_lag1", "Barriers to funding (t - 1)",
  "b_barriers_total_within", "Total legal barriers (within)",
  "b_barriers_total_lag1_within", "Total legal barriers (within; t - 1)",
  "b_advocacy_within", "Barriers to advocacy (within)",
  "b_advocacy_lag1_within", "Barriers to advocacy (within; t - 1)",
  "b_entry_within", "Barriers to entry (within)",
  "b_entry_lag1_within", "Barriers to entry (within; t - 1)",
  "b_funding_within", "Barriers to funding (within)",
  "b_funding_lag1_within", "Barriers to funding (within; t - 1)"
) %>% 
  mutate(across(everything(), ~fct_inorder(., ordered = TRUE))) %>% 
  mutate(lagging = str_detect(coef, "lag1"))
```


# Confounders

Time-varying:

- `v2x_polyarchy`
- GDP_log
- population_log
- armed_conflict
- un_trade_pct_gdp


# E~1a~: NGO laws and political terror

## Results table

```{r tbl-e1a-re}
# Build nicer column names
models_for_table_e1a_re <- models %>% 
  filter(outcome_var == "Political terror", re == "RE") %>% 
  mutate(outcome_var = recode(outcome_var, "Political terror" = "PTS"),
         explan_var = recode(explan_var, "Civil society repression" = "CS repression")) %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

# Make a named vector of original model names and nice names
models_names_table_e1a_re <- models_for_table_e1a_re %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e1a_re$model)

# Rename the columns
names(models_tbl_e1a_re) <- recode(names(models_tbl_e1a_re), 
                                   !!!models_names_table_e1a_re)

modelsummary(models_tbl_e1a_re,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

```{r tbl-e1a-rewb}
models_for_table_e1a_rewb <- models %>% 
  filter(outcome_var == "Political terror", re == "REWB") %>% 
  mutate(outcome_var = recode(outcome_var, "Political terror" = "PTS"),
         explan_var = recode(explan_var, "Civil society repression" = "CS repression")) %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

models_names_table_e1a_rewb <- models_for_table_e1a_rewb %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e1a_rewb$model)

names(models_tbl_e1a_rewb) <- recode(names(models_tbl_e1a_rewb), 
                                     !!!models_names_table_e1a_rewb)

modelsummary(models_tbl_e1a_rewb,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

## Coefficients

```{r plot-coefs-e1a}
coef_plots <- models %>% 
  filter(str_detect(model, "pts_"), !str_detect(model, "baseline")) %>% 
  mutate(re_fancy = case_when(
    re == "RE" ~ "Random effects models",
    re == "REWB" ~ "Random effects—within/between models"
  )) %>% 
  mutate(coef_draws = map(
    actual_model, 
    ~gather_draws(model = ., `.*barriers.*|.*advocacy.*|.*entry.*|.*funding.*`, regex = TRUE))) %>% 
  select(-actual_model) %>% 
  unnest(coef_draws) %>% 
  filter(!str_detect(.variable, "between")) %>% 
  left_join(coefs_clean, by = c(".variable" = "coef"))

coef_plots %>% 
  ggplot(aes(y = fct_rev(coef_clean), x = .value, fill = re_fancy)) +
  stat_halfeye(aes(alpha = lagging), .width = c(0.8, 0.95)) +
  geom_vline(xintercept = 0) +
  guides(fill = FALSE, alpha = FALSE) +
  scale_alpha_manual(values = c(1, 0.4)) +
  labs(x = "Coefficient", y = NULL) +
  facet_wrap(vars(re_fancy), ncol = 2, scales = "free_y") +
  theme_ngo()
```


## Marginal effects

```{r plot-mfx-e1a}
plot_pts_vars_lookup <- tribble(
  ~model, ~plot_var, ~plot_var_nice,
  "m_pts_total", "barriers_total", "Total legal barriers",
  "m_pts_advocacy", "advocacy", "Barriers to advocacy",
  "m_pts_entry", "entry", "Barriers to entry",
  "m_pts_funding", "funding", "Barriers to funding"
) %>% 
  mutate(plot_var_nice = fct_inorder(plot_var_nice, ordered = TRUE))

mfx <- models %>% 
  filter(str_detect(model, "_pts"), !str_detect(model, "rewb|baseline")) %>% 
  left_join(plot_pts_vars_lookup, by = "model") %>% 
  mutate(fx = map2(actual_model, plot_var, 
                   ~conditional_effects(.x, effects = .y,
                                        categorical = TRUE)[[1]])) %>% 
  select(-actual_model) %>% 
  unnest(fx)

mfx %>% 
  mutate(x_rounded = floor(effect1__)) %>% 
  group_by(x_rounded, effect2__, plot_var_nice) %>% 
  slice(1) %>% 
  ungroup() %>% 
  ggplot(aes(x = x_rounded, y = estimate__, color = effect2__)) +
  geom_pointrange(aes(ymin = lower__, ymax = upper__),
                  position = position_dodge(width = 0.2),
                  fatten = 1) +
  scale_x_continuous(breaks = 0:9) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_color_viridis_d(option = "viridis", end = 0.95) +
  labs(x = "Count of legal barriers\n",
       y = "Predicted probability of category",
       color = "Political terror scale", fill = "Political terror scale") + 
  facet_wrap(vars(plot_var_nice), scales = "free_x") +
  theme_ngo() +
  theme(panel.grid.major.x = element_blank())
```

\ 

# E~1b~: NGO laws and physical violence

## Results table

```{r tbl-e1b-re}
models_for_table_e1b_re <- models %>% 
  filter(outcome_var == "Physical violence", re == "RE") %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

model_names_tbl_e1b_re <- models_for_table_e1b_re %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e1b_re$model)

names(models_tbl_e1b_re) <- recode(names(models_tbl_e1b_re), 
                                   !!!model_names_tbl_e1b_re)

modelsummary(models_tbl_e1b_re,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

## Coefficients

```{r plot-coefs-e1b}
coef_plots <- models %>% 
  filter(str_detect(model, "clphy"), !str_detect(model, "baseline")) %>% 
  mutate(re_fancy = case_when(
    re == "RE" ~ "Random effects models",
    re == "REWB" ~ "Random effects—within/between models"
  )) %>% 
  mutate(coef_draws = map(
    actual_model, 
    ~gather_draws(model = ., `.*barriers.*|.*advocacy.*|.*entry.*|.*funding.*`, regex = TRUE))) %>% 
  select(-actual_model) %>% 
  unnest(coef_draws) %>% 
  filter(!str_detect(.variable, "between")) %>% 
  left_join(coefs_clean, by = c(".variable" = "coef"))

coef_plots %>% 
  ggplot(aes(y = fct_rev(coef_clean), x = .value, fill = re_fancy)) +
  stat_halfeye(aes(alpha = lagging), .width = c(0.8, 0.95)) +
  geom_vline(xintercept = 0) +
  guides(fill = FALSE, alpha = FALSE) +
  scale_alpha_manual(values = c(1, 0.4)) +
  labs(x = "Coefficient", y = NULL) +
  facet_wrap(vars(re_fancy), ncol = 2, scales = "free_y") +
  theme_ngo()
```

## Marginal effects

```{r plot-mfx-e1b}
plot_clphy_vars_lookup <- tribble(
  ~model, ~plot_var, ~plot_var_nice,
  "m_clphy_total", "barriers_total", "Total legal barriers",
  "m_clphy_advocacy", "advocacy", "Advocacy",
  "m_clphy_entry", "entry", "Entry",
  "m_clphy_funding", "funding", "Funding"
) %>% 
  mutate(plot_var_nice = fct_inorder(plot_var_nice, ordered = TRUE))

mfx <- models %>% 
  filter(str_detect(model, "clphy"), !str_detect(model, "rewb|baseline")) %>% 
  left_join(plot_clphy_vars_lookup, by = "model") %>% 
  mutate(fx = map2(actual_model, plot_var, 
                   ~conditional_effects(.x, effects = .y)[[1]])) %>% 
  select(-actual_model) %>% 
  unnest(fx)

mfx %>% 
  mutate(x_rounded = floor(effect1__)) %>% 
  group_by(x_rounded, plot_var_nice) %>% 
  slice(1) %>% 
  ungroup() %>% 
  ggplot(aes(x = x_rounded, y = estimate__, color = plot_var_nice)) +
  geom_line(size = 0.5, color = "grey90") +
  geom_pointrange(aes(ymin = lower__, ymax = upper__),
                  fatten = 1) +
  scale_x_continuous(breaks = 0:9) +
  scale_color_viridis_d(option = "plasma", end = 0.8) +
  guides(color = FALSE) +
  labs(x = "Count of legal barriers",
       y = "Predicted physical violence index\n(higher values = less violence)") +
  facet_grid(cols = vars(plot_var_nice), scales = "free_x", space = "free_x") +
  theme_ngo() +
  theme(panel.grid.major.x = element_blank())
```

\ 

# E~1c~: NGO laws and civil liberties

## Results table

```{r tbl-e1c-re}
models_for_table_e1c_re <- models %>% 
  filter(outcome_var == "Private civil liberties", re == "RE") %>% 
  mutate(model_name = glue("{outcome_var} (t + 1)<br>({explan_var}; {re})"))

model_names_tbl_e1c_re <- models_for_table_e1c_re %>% 
  pull(model_name) %>% 
  set_names(models_for_table_e1c_re$model)

names(models_tbl_e1c_re) <- recode(names(models_tbl_e1c_re), 
                                   !!!model_names_tbl_e1c_re)

modelsummary(models_tbl_e1c_re,
             statistic = "[{conf.low}, {conf.high}]",
             coef_map = coef_list,
             gof_omit = "ELPD",
             escape = FALSE,
             notes = list("Posterior means; 95% credible intervals in brackets"))
```

## Coefficients

```{r plot-coefs-e1c}
coef_plots <- models %>% 
  filter(str_detect(model, "clpriv"), !str_detect(model, "baseline")) %>% 
  mutate(re_fancy = case_when(
    re == "RE" ~ "Random effects models",
    re == "REWB" ~ "Random effects—within/between models"
  )) %>% 
  mutate(coef_draws = map(
    actual_model, 
    ~gather_draws(model = ., `.*barriers.*|.*advocacy.*|.*entry.*|.*funding.*`, regex = TRUE))) %>% 
  select(-actual_model) %>% 
  unnest(coef_draws) %>% 
  filter(!str_detect(.variable, "between")) %>% 
  left_join(coefs_clean, by = c(".variable" = "coef"))

coef_plots %>% 
  ggplot(aes(y = fct_rev(coef_clean), x = .value, fill = re_fancy)) +
  stat_halfeye(aes(alpha = lagging), .width = c(0.8, 0.95)) +
  geom_vline(xintercept = 0) +
  guides(fill = FALSE, alpha = FALSE) +
  scale_alpha_manual(values = c(1, 0.4)) +
  labs(x = "Coefficient", y = NULL) +
  facet_wrap(vars(re_fancy), ncol = 2, scales = "free_y") +
  theme_ngo()
```

## Marginal effects

```{r plot-mfx-e1c}
plot_clpriv_vars_lookup <- tribble(
  ~model, ~plot_var, ~plot_var_nice,
  "m_clpriv_total", "barriers_total", "Total legal barriers",
  "m_clpriv_advocacy", "advocacy", "Advocacy",
  "m_clpriv_entry", "entry", "Entry",
  "m_clpriv_funding", "funding", "Funding"
) %>% 
  mutate(plot_var_nice = fct_inorder(plot_var_nice, ordered = TRUE))

mfx <- models %>% 
  filter(str_detect(model, "clpriv"), !str_detect(model, "rewb|baseline")) %>% 
  left_join(plot_clpriv_vars_lookup, by = "model") %>% 
  mutate(fx = map2(actual_model, plot_var, 
                   ~conditional_effects(.x, effects = .y)[[1]])) %>% 
  select(-actual_model) %>% 
  unnest(fx)

mfx %>% 
  mutate(x_rounded = floor(effect1__)) %>% 
  group_by(x_rounded, plot_var_nice) %>% 
  slice(1) %>% 
  ungroup() %>% 
  ggplot(aes(x = x_rounded, y = estimate__, color = plot_var_nice)) +
  geom_line(size = 0.5, color = "grey90") +
  geom_pointrange(aes(ymin = lower__, ymax = upper__),
                  fatten = 1) +
  scale_x_continuous(breaks = 0:9) +
  scale_color_viridis_d(option = "plasma", end = 0.8) +
  guides(color = FALSE) +
  labs(x = "Count of legal barriers",
       y = "Predicted civil liberties index\n(higher values = better protection)") +
  facet_grid(cols = vars(plot_var_nice), scales = "free_x", space = "free_x") +
  theme_ngo() +
  theme(panel.grid.major.x = element_blank())
```
