---
title: "Canary in the Coal Mine: Anti-NGO Legislation as a Predictor of Civil Society Repression"
author: "Suparna Chaudhry and Andrew Heiss"
date: "Last run: `r format(Sys.time(), '%F')`"
---

## Abstract

Many countries across the globe are increasingly cracking down on civil society groups through legal restrictions. While research on democratic backsliding has tended to focus on rights and institutions in the electoral arena, this new wave of laws—many of which appear mundane on their face—represent a bureaucratic form of repressive that could be indicative of more severe human rights abuses and backsliding. This is especially the case for electoral democracies, which unlike autocracies do not aggressively and openly attack civic space. In this paper, we ask: do legal crackdowns on NGOs predict broader civil society repression? We argue that this is the case because anti-NGO laws are among the most subtle means of repression and attract the least least domestic and international condemnation, as many audiences mistake this repression as regulation and are not personally affected by it. These laws also make it easier for states to prevent and deter future large-scale popular mobilization. Using original data on civil society restrictions over the last three decades, we test whether NGO crackdown is a predictor of attacks on journalists, independent media, academic freedom, and freedoms of expression and association. This project has important implications: if crackdown on NGOs is indeed an early warning, it can potentially prevent further deteriorations in space for civil society. 
